### ISSUE TITLE
Issue : Github Action .env 환경 변수 이슈

### ISSUE THREAD

**Issue by TLOWAC** [dnd-side-project/dnd-10th-1-backend#19]
# 🚑 Hotfix

## 어떤 버그가 있었나요?

AWS 인프라 설정 작업 이후 Github Action 배포 스크립트를 테스트 하는 과정에서 이슈가 발생하였습니다.
<img width="793" alt="image" src="https://github.com/dnd-side-project/dnd-10th-1-backend/assets/58043975/c891dd21-1217-4b1e-ba21-ecf9e0a6c0b1">

해당 이슈의 근본적인 원인은 환경 변수 파일인 .env.local, .env.dev, .env.prod 를 public repo 에 업로드하지 않은 상태로 
Github Action 에서 .env.dev 등의 환경 변수값을 사용해 `yarn build` 명령어를 실행하는데 있었습니다.

그로인해 `yarn build` 명령어의 실행 결과로 생성되는 빌드 폴더인 dist 폴더는 생성되지 않았습니다.
따라서 step 단위의 Github Action 작업에서 빌드 폴더를 공유하는 단계인 Upload Artifact 와 Download Artifact 가 정상적으로 동작하지 않았고
이로인해 최종적인 Deploy step 에서 배포가 실패하게 되었습니다.
<img width="455" alt="image" src="https://github.com/dnd-side-project/dnd-10th-1-backend/assets/58043975/9afc3532-76ac-4c88-a889-09abcf380d8b">

## 어떤 작업을 할 예정인가요?
.env.dev 와 .env.prod 에 대한 내용은 Public Repo 이기 때문에 선뜻 업로드하기에는 꺼려집니다. 
따라서 아래의 3가지 방법을 생각해볼 수 있습니다.

- Github Action 에서 Step[Create Env File] 추가
- 환경 변수 관리 방법의 변경 기존 : dotenv -> AWS Secret Manger 
- AWS CodeBuild, CodeDeploy 를 활용한 배포 방식 변경

## 기타

**Comment by TLOWAC** [comment]
@hyebinnn

**Comment by TLOWAC** [comment]
Github Setting 에서 Envionment > Secrets 를 추가하고 Github Action 에 `Set Environment variables` 단계를 추가하는 
방향으로 작업을 진행하였습니다.

### Github Action 에 Set Envionment 스텝 추가
```yaml
- name: Set environment variables
  env:
    NODE_ENV: ${{ secrets.NODE_ENV }}
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
    PORT: ${{ secrets.PORT }}
    SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  run: |
    echo "NODE_ENV=${NODE_ENV}" >> .env.dev
    echo "DATABASE_URL=${DATABASE_URL}" >> .env.dev
    echo "PORT=${PORT}" >> .env.dev
    echo "SERVICE_NAME=${SERVICE_NAME}" >> .env.dev
```


### Build 폴더의 Upload Artifact 스텝 통과 확인
<img width="1259" alt="image" src="https://github.com/dnd-side-project/dnd-10th-1-backend/assets/58043975/06e8e7ad-05c3-4881-97cc-0fdeabab7a03">

### Build 폴더의 Download Artifact 스텝 통과 확인
<img width="493" alt="image" src="https://github.com/dnd-side-project/dnd-10th-1-backend/assets/58043975/6f72c659-64fa-455c-b08d-3282e3720c9f">
